### ISSUE TITLE
Prevent collision/overwrite with git-extras

### ISSUE THREAD

**Issue by ignasi35** [renatocaval/oh-my-git#7]
Til [`git-extras`](https://github.com/tj/git-extras) (thanks @dwijnand) and I think there could be some overlap or ambiguity. For example, `gca` may mean different things for each project (extras vs oh-my-git).

**Comment by octonato** [comment]
`gca` is not defined by oh-my-git. 

I don't know about you. By I do have git-extras and lots of the commands used by oh-my-git comes from git-extras. You probably have it already.

**Comment by ignasi35** [comment]
I wasn't aware of `git-extras` and I think I didn't have it installed (until this morning). 

> lots of the commands used by oh-my-git comes from git-extras

I'm not sure I understood that. If `oh-my-git` depends on `git-extras` we shoudl add the requirement in the `README` and mention `oh-my-git`'s relation to that in that "it was an inspiration" or "assumes you're comformtable with aliases like `gca`".

> gca is not defined by oh-my-git.

I know. Since I discovered `git-extras` today I was trying to point out how both projects complement and how `oh-my-git` can piggy-back from that to reuse conventions instead of reinventing the wheel.
